import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "./common/CustomThemeProvider";
import BProgressProvider from "./common/BProgressProvider";
import { NavBar, Footer } from "@/components/NavBarAndFooter";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CACHE_PROVIDER_OPTIONS = {
  key: "sds",
  prepend: true,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className={`${inter.className} h-full`}>
        <BProgressProvider>
          <AppRouterCacheProvider options={CACHE_PROVIDER_OPTIONS}>
            <CustomThemeProvider>
              <main className="flex flex-col min-h-screen">
                <NavBar />
                <div className="flex-grow">{children}</div>
                <Footer />
              </main>
            </CustomThemeProvider>
          </AppRouterCacheProvider>
        </BProgressProvider>
      </body>
    </html>
  );
}
