import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomThemeProvider } from "./common/CustomThemeProvider";
import { NavigationHeader, NavigationFooter } from "@czi-sds/components";
import BProgressProvider from "./common/BProgressProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const CACHE_PROVIDER_OPTIONS = {
  key: "sds",
  prepend: true,
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <BProgressProvider>
          <AppRouterCacheProvider options={CACHE_PROVIDER_OPTIONS}>
            <CustomThemeProvider>
              <main>
                <NavigationHeader title="Placeholder Site Title" />
                {children}
                <NavigationFooter title="Placeholder Site Title" />
              </main>
            </CustomThemeProvider>
          </AppRouterCacheProvider>
        </BProgressProvider>
      </body>
    </html>
  );
}
